GET http://localhost:5000/store/view-table
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIiLCJwYXNzd29yZCI6IjEyMyIsImlhdCI6MTY4MTQ1MzY3NX0.V2ZqV1XuAnH_JvUfR0zCvXKcA8So3S-FWt8B4iZv_QA

###

POST http://localhost:5000/store/login
Content-Type: application/json

{
    "username": "user",
    "password": "123"
}