GET http://localhost:5000/store/view-table
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlBNIiwicGFzc3dvcmQiOiI_QDEyM1BNP0AxOTgzIiwiaWF0IjoxNjgxNDU1NzI3fQ.HSw0ZbXwaDg6iE3ERX_xE-NbY1ETIVZ8dPYRpuILmPc

###

POST http://localhost:5000/store/login
Content-Type: application/json

{
    "username": "PM",
    "password": "?@123PM?@1983"
}

###
GET http://localhost:5000/auth/api