services:
  backend:
    restart: always
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
    command: bash -c "python manage.py migrate &&
                      pip install -r requirements.txt &&
                      python manage.py runserver 0.0.0.0:8000"

  # frontend:
  #   restart: always
  #   build: ./pm-store
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - "./pm-store:/pm-store"
  #     - "/pm-store/node_modules"
  #   command: > 
  #     bash -c "cp -rfu /cache/node_modules/. /pm-store/node_modules/  
  #     && npm start"
  #   depends_on:
  #     - backend
  #   environment:
  #     - WATCHPACK_POLLING=true

  db:
    image: postgres
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres