# Generated by Django 4.2.7 on 2023-12-13 13:24

import auths.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buyers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(unique=True)),
                ('phone', models.CharField(unique=True)),
                ('name', models.CharField()),
                ('address', models.CharField()),
                ('password', models.CharField()),
                ('profilepic', models.FileField(upload_to=auths.models.profilepic_path)),
            ],
            options={
                'verbose_name_plural': 'Buyers',
            },
        ),
    ]
