# Generated by Django 4.2.7 on 2023-12-14 13:40

import auths.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(unique=True)),
                ('phone', models.CharField(unique=True)),
                ('name', models.CharField()),
                ('address', models.CharField()),
                ('password', models.CharField()),
                ('profilepic', models.FileField(upload_to=auths.models.seller_profilepic_path)),
            ],
        ),
        migrations.RenameModel(
            old_name='Buyers',
            new_name='Buyer',
        ),
        migrations.AlterModelOptions(
            name='buyer',
            options={},
        ),
    ]
