# Generated by Django 4.2.7 on 2023-12-14 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0003_shop'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shop',
        ),
    ]
