# Generated by Django 4.2.7 on 2023-12-14 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('description', models.CharField()),
                ('address', models.CharField()),
                ('business_name', models.CharField()),
                ('isCG', models.BooleanField()),
                ('GST', models.CharField()),
                ('bank_account', models.CharField()),
            ],
        ),
    ]
