# Generated by Django 4.2.7 on 2023-12-23 14:19

from django.db import migrations, models
import django.db.models.deletion
import seller.models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0004_delete_shop'),
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='business_name',
            new_name='instagram_handle',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='isCG',
        ),
        migrations.AddField(
            model_name='shop',
            name='banner',
            field=models.FileField(default='', upload_to=seller.models.banner_image_address),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shop',
            name='owner',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='auths.seller', to_field='email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shop',
            name='shop_image',
            field=models.FileField(default='', upload_to=seller.models.shop_image_address),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shop',
            name='yt_handle',
            field=models.CharField(default=''),
            preserve_default=False,
        ),
    ]
