# Generated by Django 4.2.7 on 2023-12-27 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0004_delete_shop'),
        ('seller', '0002_rename_business_name_shop_instagram_handle_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shop',
            unique_together={('owner', 'name')},
        ),
    ]
