# Generated by Django 4.2.7 on 2023-12-28 07:59

from django.db import migrations, models
import seller.models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_alter_shop_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('description', models.CharField()),
                ('price', models.CharField()),
                ('category', models.CharField()),
                ('brand', models.CharField()),
                ('stock', models.CharField()),
                ('size', models.CharField()),
                ('image1', models.FileField(upload_to=seller.models.product_image_address)),
                ('image2', models.FileField(null=True, upload_to=seller.models.product_image_address)),
                ('image3', models.FileField(null=True, upload_to=seller.models.product_image_address)),
                ('image4', models.FileField(null=True, upload_to=seller.models.product_image_address)),
                ('image5', models.FileField(null=True, upload_to=seller.models.product_image_address)),
                ('video', models.CharField()),
                ('hashtags', models.CharField()),
            ],
        ),
    ]
