# Generated by Django 4.2.7 on 2023-12-28 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0004_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shop_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='seller.shop'),
            preserve_default=False,
        ),
    ]
