# Generated by Django 4.2.7 on 2023-12-28 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0005_product_shop_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='shop_name',
            new_name='shop',
        ),
    ]
