import React from "react";
import styled from "./TermsAndConditions.module.css"; // Import your CSS file

const TermsAndConditions = () => {
    const termsAndConditionsText = `
    TERMS OF SERVICE AGREEMENT
    LAST REVISION: 01-September-2021
    Please read these terms and conditions carefully. These T&C, as modified or amended from time to time, are a binding contract between the company and you. If you visit, use, or shop at the site (or any future site operated by the company, you accept these T&C. In addition, when you use any current or future services of the company or visit or purchase from any business affiliated with the company or third party vendors, whether or not included in the site, you also will be subject to the guidelines and conditions applicable to such service or merchant. If these conditions are inconsistent with such guidelines and conditions, such guidelines and conditions will control.
    Introduction to Pandri Market Private Limited
    The website, pandrimarket.com is operated under license by Pandri Market Private Limited, a company duly incorporated under the Companies Act, 1956 of India and having its office at MIG 29 Indiravati Colony, Pandri Link Rd, RajaTalab, Civil Lines, Raipur, Chhattisgarh 492001.  Contact us at admin@pandrimarket.com.
    “Pandrimarket" is a registered trademark.
    General Introduction 
    You ("you" or "End User" or "your" or "Buyer" or "Customer") are required to read and accept all of the terms and conditions laid down in this Terms and Conditions ("Terms and Conditions" or "T&C" or "Terms" or "Agreement") and the linked Privacy Policy, before you may use www.pandrimarket.com (hereinafter referred to as "Site" or "pandrimarket.com" or "we" or "our"). The Site allows you to browse, select and purchase high fashion and lifestyle products online, goods and accessories, vouchers and coupons ("Goods" or "Products" or "Services")
    This T&C is effective upon acceptance and governs the relationship between you and Pandri Market Private Limited (hereinafter "Company") including the sale and supply of any Products on the site. If this T&C conflicts with any other document, the T&C will prevail for the purposes of usage of the Site. If you do not agree to be bound by this T&C and the Privacy Policy, you may not use the Site in any way. The Company facilitates goods and services to you subject to the T&C. Pandri Market Private Limited will alert you that changes or revisions have been made by indicating at the top of this Agreement the date it was last revised. The changed or revised Agreement will be effective immediately after it is posted on this Website. Your use of the Website following the posting any such changes or of a revised Agreement will constitute your acceptance of any such changes or revisions. Pandri Market Private Limited encourages you to review this Agreement whenever you visit the Website to make sure that you understand the terms and conditions governing the use of the Website. This Agreement does not alter in any way the terms or conditions of any other written agreement you may have with Pandri Market Private Limited for other products or services. If you do not agree to this Agreement (including any referenced policies or guidelines), please immediately terminate your use of the Website. If you would like to print this Agreement, please click the print button on your browser toolbar. If we make changes to our T&C and Privacy Policy and you continue to use our Site, you are impliedly agreeing to the revised T&C and Privacy Policy expressed herein.
    If this T&C conflicts with any other document, the T&C will prevail for the purposes of usage of the Site. As a condition of purchase, the Site requires your permission to send you administrative and promotional emails. We will send you information regarding your account activity and purchases, as well as updates about our products and promotional offers. You can opt-out of our promotional emails anytime by clicking the unsubscribe link at the bottom of any of our email correspondences. Please see our Privacy Policy for details. We shall have no responsibility in any manner whatsoever regarding any promotional emails or SMS/MMS sent to you. The offers made in those promotional emails or SMS/MMS shall be subject to change at the sole discretion of the Suppliers listed with the Company and the Company owes no responsibility to provide you any information regarding such change.
    By placing an order, you make an offer to us to purchase products you have selected based on standard Site restrictions, Merchant specific restrictions, and on the terms and conditions stated below.
    You will be required to create an account in order to purchase any product from the Site. This is required so we can provide you with easy access to print your orders and view your past purchases
    The Site takes no responsibility for the services or products that are sold or supplied by third party vendors. The Company makes no warranty to their end users for the quality, safety, usability, or other aspects of a product or service that is supplied by a Merchant, the Company takes no responsibility for the product being offered, and the User takes responsibility for his or her own actions in using those products or thoroughly doing market research before availing goods and services from the site.
    Privacy Policy and Other Policies / Statements
    By subscribing to or using any of our services, you hereby agree to have read and understood the privacy policy and other policies, statements, and information put on the website.
    I. PRODUCTS
    Terms of Offer. This Website offers for sale of certain products/providing the services (the "Products/ service"). By placing an order for Products through this Website, you agree to the terms set forth in this Agreement. 
    Customer Solicitation 
    When you use the Site or send emails to admin@pandrimarket.com, you are communicating with pandrimarket. electronically. You consent to receive communications from pandrimarket.com electronically. pandrimarket.com will communicate with you by email, SMS or by posting notices on the Site. You agree that all agreements, notices, disclosures and other communications that we provide to you electronically satisfy any legal requirement that such communications be in writing.
    Unless you notify our third-party call center reps or direct Pandri Market Private Limited sales reps, while they are calling you, of your desire to opt out from further direct company communications and solicitations, you are agreeing to continue to receive further emails and call solicitations Pandri Market Private Limited and its designated in-house or third-party call team(s).  
    Opt-Out Procedure
    We provide 3 easy ways to opt out of from future solicitations. 
    1. You may use the opt-out link found in an email solicitation that you may receive. 
    2. You may also choose to opt out, via sending your email address to admin@pandrimarket.com.
     3. You may send a written remove request to Pandri Market Private Limited                                          MIG 29 Indiravati Colony, Pandri Link Rd, RajaTalab, Civil Lines, Raipur, Chhattisgarh 492001.
    Billing
    The price of goods and services you purchase is inclusive of GST. The GST charged shall depend upon the destination where the order has to be shipped. The tax rate applied to the order will be the combined tax rate for both state and local tax rates. The respective sellers/suppliers reserve the right to collect taxes for shipping charges wherever applicable.
    Returns and Exchange
    You acknowledge that these terms of returns and exchange are limited to the products and subject to other rules and conditions mentioned in this portal and that these terms of returns and exchange are not available at the listed items are governed by the third party seller/supplies registered in this portal and any return or exchange of items would be on the terms and conditions of third party seller/supplier and directly to their warehouse or communication address mentioned in their respective invoices. pandrimarket.com only facilitate you the contact address or make you communicate with the third party Seller/ Supplier. For your knowledge please consider the below general rules before initiating any return or exchange. 
    For this purpose, Seller/ Supplier must receive the merchandise within 7 days from the date it was shipped to you. Items must be unused, unworn, unwashed and undamaged by you. Goods will be returned only if they are returned in their original packaging, including hangers, polybags, hang tags on garments, shoe boxes, dust bags, and gift boxes. No returns will be applicable on select items which will be mentioned explicitly with a “No Return’ tag. All conditions applicable to return of goods shall also apply to exchange of goods. To return an item, the customer must write to us at admin@pandrimarket.com, – a prompt response is assured to such emails. If you are not satisfied with the product received by you for any reason you may have the option to exchange and at the sole discretion of the supplier/ Seller to receive a refund. pandrimarket.com is not liable for any damages caused to the Product during transit.
    Our terms and conditions pertaining to returns and exchange can be accessed through the following link and we hereby assume that the same has been read and agreed by you.
    Cancellations
    In case of requests for order cancellations, pandrimarket.com reserves the right to accept or reject requests for order cancellations for any reason. As part of usual business practice, if we receive a cancellation notice and the order has not been processed/approved by us, we shall cancel the order and refund the entire amount. A request for cancellation of the order shall be valid and accepted only if they are made within 24 hours of making the order on the Site. We will not be able to cancel orders that have already been processed or orders for which request for cancellation is made after the expiry of 24 hours from the time of placing the order. pandrimarket.com has the full right to decide whether an order has been processed or not. The customer agrees not to dispute the decision made by pandrimarket.com and accept pandrimarket.com’s the decision regarding the cancellation. In the event of cancellation of the order by the customer pandrimarket.com shall not refund the voucher, if any used against such order. 
    Cancellation by pandrimarket.com
    Please note that there may be certain orders that we are unable to accept and must cancel. We reserve the right, at our sole discretion, to refuse or cancel any order for any reason. Some situations that may result in your order being canceled shall include limitations on quantities available for purchase, inaccuracies or errors in product or pricing information, problems identified by our credit and fraud avoidance department or any defect regarding the quality of the product. We may also require additional verifications or information before accepting any order. We will contact you if all or any portion of your order is canceled or if additional information is required to accept your order. If your order is canceled after your credit card has been charged, the said amount will be reversed back in your Card Account. Any type of voucher used in these orders shall be pushed back into the user's account in case of cancellation by pandrimarket.com).
    Refund Clause 
    For the purpose of this clause, account credit means a credit issued to your account for the entire purchase amount minus the shipping costs. Your account credit can be used towards your next purchase with pandrimarket.com.
    Please also see our Return Policy FAQs for further information.
    Offers, Promotional Schemes, and Vouchers
    pandrimarket.com reserves the right to change/modify/add/delete any of the terms and conditions prevailing on the different promotional schemes (including but not limited to refer-a-friend and other types of vouchers) it introduces in the market from time to time. pandrimarket.comat its discretion can withdraw a particular scheme from the website or market. In case of any query, you can connect with us on admin@pandrimarket.com.
    Lost or Stolen Coupons
    The Customer must notify pandrimarket.com immediately if the Coupon is lost, stolen, mutilated, not received or if the customer suspects that the Coupon is being used without his/her consent. In the case of loss or theft of the Coupon, the Customer must call us at [9244092424] during our hours of operation or email us at admin@pandrimarket.com. pandrimarket.com on the receipt of this information will act per its standard operating procedures.
    If the lost Coupon is subsequently received by the Customer, it should be destroyed and must not be used. Only the replacement/new Coupon issued by pandrimarket.com can be used.
    Guarantee of Products/Services
    pandrimarket.com hereby disclaims any guarantee of the accuracy in terms of finish and appearance of the final product as ordered by the user. The quality of any products, services, information, or other material purchased or obtained by you through the website may or may not meet your expectations.
    II. WEBSITE
    This Agreement sets forth the terms and conditions that apply to the use of the Site by the User. By using this Site, the User agrees to comply with all of the T&C hereof. The right to use the Site is personal to the User and is not transferable to any other person or entity. The User shall be responsible for protecting the confidentiality of their password(s) if any. The User acknowledges that, although the internet is often a secure environment, sometimes there are interruptions in service or events that are beyond the control of the Company, and the Company shall not be responsible for any data lost while transmitting information on the internet. While it is the Company's objective to make the Site accessible 24 hours per day, 7 days per week, the Site may be unavailable from time to time for any reason including, without limitation, routine maintenance. You understand and acknowledge that due to circumstances both within and outside of the control of the Company, access to the Site may be interrupted, suspended or terminated from time to time. The Company shall have the right at any time to change or discontinue any aspect or feature of the Site, including, but not limited to, content, hours of availability and equipment needed for access or use. Further, the Company may discontinue disseminating any portion of information or category of information may change or eliminate any transmission method and may change transmission speeds or other signal characteristics.
    Content; Intellectual Property; Third Party Links
     In addition to making Products available, this Website also offers information and marketing materials. This Website also offers information, both directly and through indirect links to third-party websites, about nutritional and dietary supplements. Pandri Market Private Limited does not always create the information offered on this Website; instead, the information is often gathered from other sources. To the extent that Pandri Market Private Limited does create the content on this Website, such content is protected by intellectual property laws of India, foreign nations, and international bodies. Unauthorized use of the material may violate copyright, trademark, and/or other laws. You acknowledge that your use of the content on this Website is for personal, non-commercial use. Any links to third-party websites are provided solely as a convenience to you. Pandri Market Private Limited does not endorse the contents on any such third-party websites. Pandri Market Private Limited is not responsible for the content of or any damage that may result from your access to or reliance on these third-party websites. If you link to third-party websites, you do so at your own risk. 
    Use of Website
    Pandri Market Private Limited is not responsible for any damages resulting from the use of this website by anyone. You will not use the Website for illegal purposes. You will (1) abide by all applicable local, state, national, and international laws and regulations in your use of the Website (including laws regarding intellectual property), (2) not interfere with or disrupt the use and enjoyment of the Website by other users, (3) not resell material on the Website, (4) not engage, directly or indirectly, in transmission of "spam", chain letters, junk mail or any other type of unsolicited communication, and (5) not defame, harass, abuse, or disrupt other users of the Website 
    Linking to this website
    You may provide links to our website homepage. However, it should not suggest our association with you in any form or the other. Also, doing so must not bring any legal or reputation damage to our website.
    The User shall be responsible for obtaining and maintaining telephone, computer hardware and other equipment needed for access to and use of the Site and all charges related thereto. The Company shall not be liable for any damages to the User's equipment resulting from the use of the Site.
    License
    By using this Website, you are granted a limited, non-exclusive, non-transferable right to use the content and materials on the Website in connection with your normal, non-commercial, use of the Website. You may not copy, reproduce, transmit, distribute, or create derivative works of such content or information without express written authorization from Pandri Market Private Limited or the applicable third party (if the third-party content is an issue).
    WE HEREBY HOLD NO LIABILITY TO ANY SORT OF DAMAGE OR HARM CAUSED TO YOUR SOFTWARE, DATA OR COMPUTER DEVICE BY DOWNLOADING CONTENT FROM THIS WEBSITE.
    Site-Provided Messages and Postings
    The Site may provide users with the ability to send email messages to other users and non-users and to post messages on the Site. Pandri Market Private Limited is under no obligation to review any messages, information or content ("Postings") posted on the Site by users and assumes no responsibility or liability relating to any such Postings. Notwithstanding the above, Pandri Market Private Limited may from time to time monitor the Postings on the Site and may decline to accept and/or remove any email or Postings. You understand and agree not to use any functionality provided by the Site to post content or initiate communications that contain: (i) Any unlawful, harmful, threatening, abusive, harassing, defamatory, vulgar, obscene, profane, hateful, racially, ethnically or otherwise objectionable material of any kind, including, but not limited to, any material which encourages conduct that would constitute a criminal offense, give rise to civil liability or otherwise violate any applicable local, state, national or international law. (ii) Advertisements or solicitations of any kind. (iii) Impersonate others or provide any kind of false information. (iv) Personal information such as messages which state phone numbers, account numbers, addresses, or employer references. (v) Messages by non-spokesperson employees of Pandri Market Private Limited purporting to speak on behalf of Pandri Market Private Limited or containing confidential information or expressing opinions concerning Pandri Market Private Limited. (vi) Messages that offer unauthorized downloads of any copyrighted or private information. (vii) Multiple messages placed within individual folders by the same user restating the same point. (viii) Chain letters of any kind. (ix) Identical (or substantially similar) messages to multiple recipients advertising any product or service, expressing a political or other similar messages, or any other type of unsolicited commercial message. This prohibition includes but is not limited to a) Using Pandri Market Private Limited invitations to send messages to people who don't know you or who are unlikely to recognize you as a known contact; b) Using the Site to connect to people who don't know you and then sending unsolicited promotional messages to those direct connections without their permission; and c) Sending messages to distribution lists, newsgroup aliases, or group aliases.
    Registration & Security
    Once registered, you will receive a confirmation mail on your registered email address.
    You are responsible for maintaining the confidentiality of the password and account and are fully responsible for all activities that occur under your password or account.
    You will notify the Pandri Market Private Limited team immediately of any unauthorized use of your password or account or any other breach of security.
    Pandri Market Private Limited cannot and will not be liable for any loss or damage arising from your failure to comply.
    Membership Eligibility
    The Service is not available to minors under the age of 18 or to any users suspended or removed from the system by Pandri Market Private Limited for any reason. Users may not have more than one account. Maintaining more than one account by a user shall amount to fraudulent act on part of the user and attract actions against such user in accordance with the terms of the clause on fraudulent/declined transactions below. Additionally, users are prohibited from selling, trading, or otherwise transferring your Pandri Market Private Limited account to another party. If you do not qualify, you may not use the Service or the Site.
    The Company owns no responsibility in any manner over any dispute arising out of transactions by any third party using your account/e-mail provided by you to the Company or payments made by your credit card by any third party.
    iii. Terms of Sale
    Once you place an order with pandrimarket.com, you thus agree to abide by the following terms and conditions:
    All the orders placed with us are subject to the availability of the desired product.
    Once an order is placed, an acknowledgment e-mail stating the confirmation of your order will be received by you. Please note that this acknowledgment does not mean the acceptance of your order. Your order is only accepted once the payment is received from your credit/debit card/account.
    A standard authorization check is carried out on your payment card once your order is received by us. This is done solely to make sure that you have sufficient funds and thus your transaction can be carried out without any hindrance.
    We make our best efforts to ensure that the product descriptions and set prices are accurate. However, an error may occur. If it is discovered by us that the mentioned price at which you placed the order is incorrect, you will be informed by us at the earliest. You will be given the following two options –
    You can reconfirm your order at the corrected new price;
    If you do not wish to make the purchase any longer, you can cancel your order;
    Free delivery may be subject to minimum order value as per the Shipping Policy;
    In case we are unable to contact you regarding the price change, your order will be considered as canceled, and the debited amount will be refunded back to your respective account.
    By placing an order, you make an offer to us to purchase products you have selected based on standard Site restrictions, Merchant specific restrictions, and on the terms and conditions stated below.
    
    We strive to provide you with the best prices possible on products and/or services you buy from pandrimarket.com, however, pandrimarket.com does not guarantee that the price will be the lowest in the city, region or geography. Prices and availability are subject to change without any prior notice. The prices mentioned on the Site are not subject to comparison with the same or similar product(s) and/or service(s) available through any online or offline sale. The pricing is subject to pandrimarket.com pricing policy and the prices shall be determined only at pandrimarket.comsole discretion.
     Fraudulent/Declined Transactions
    Our fraud detection team constantly monitors the user's account in order to avoid fraudulent accounts and transactions. Users with more than one account or availing referral vouchers fraudulently shall be liable for legal actions under the law and Pandri Market Private Limited reserves the right to recover the cost of goods, collection charges, and lawyer’s fees from persons using the Site fraudulently. Pandri Market Private Limited reserves the right to initiate legal proceedings against such persons for fraudulent use of the Site and any other unlawful acts or omissions in breach of these terms and conditions. In the event of detection of any fraudulent or declined transaction, prior to initiation of legal actionsPandri Market Private Limited reserves the right to immediately delete such account and dishonor all past and pending orders without any liability. For the purpose of this clausePandri Market Private Limited shall owe no liability for any refunds. The user can view all vouchers issued to them under the "My Basket" section after making a selection of the minimum purchase value.
    Disclaimer of warranties
    ALL CONTENT, PRODUCTS, AND SERVICES ON THE SITE, OR OBTAINED FROM A WEBSITE TO WHICH THE SITE IS LINKED (A "LINKED SITE") ARE PROVIDED TO YOU "AS IS" WITHOUT WARRANTY OF ANY KIND EITHER EXPRESS OR IMPLIED INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE, TITLE, NON-INFRINGEMENT, SECURITY OR ACCURACY. ALL WARRANTIES, IF ANY, RELATING TO THE PRODUCT AND SERVICES WOULD BE PROVIDED BY THE MANUFACTURER/SUPPLIER OF SUCH PRODUCT AND NOT BY Pandri Market Private Limited. ANY CLAIM IN RELATION TO THE SAME SHOULD BE RAISED AGAINST RESPECTIVE MANUFACTURER/SUPPLIER AND NOT Pandri Market Private Limited IN ANY CASE WHATSOEVER. Pandri Market Private Limited DOES NOT ENDORSE AND IS NOT RESPONSIBLE FOR
     (A) THE ACCURACY OR RELIABILITY OF ANY OPINION, ADVICE OR STATEMENT MADE THROUGH THE SITE BY ANY PARTY OTHER THAN Pandri Market Private Limited, 
    (B) ANY CONTENT PROVIDED ON LINKED SITES OR 
    (C) THE CAPABILITIES OR RELIABILITY OF ANY PRODUCT OR SERVICE OBTAINED FROM A LINKED SITE. 
    OTHER THAN AS REQUIRED UNDER APPLICABLE CONSUMER PROTECTION LAW, UNDER NO CIRCUMSTANCE WILL Pandri Market Private Limited BE LIABLE FOR ANY LOSS OR DAMAGE CAUSED BY A USER'S RELIANCE ON INFORMATION OBTAINED THROUGH THE SITE OR A LINKED SITE, OR USER'S RELIANCE ON ANY PRODUCT OR SERVICE OBTAINED FROM A LINKED SITE. IT IS THE RESPONSIBILITY OF THE USER TO EVALUATE THE ACCURACY, COMPLETENESS OR USEFULNESS OF ANY OPINION, ADVICE OR OTHER CONTENT AVAILABLE THROUGH THE SITE, OR OBTAINED FROM A LINKED SITE. PLEASE SEEK THE ADVICE OF PROFESSIONALS, AS APPROPRIATE, REGARDING THE EVALUATION OF ANY SPECIFIC OPINION, ADVICE, PRODUCT, SERVICE, OR OTHER CONTENT.
    Furthermore, IT NEEDS TO BE MENTIONED THAT IN CASE OF CERTAIN JURISDICTIONS WHICH DOES NOT ALLOW THE LIMITATION OR EXCLUSION OF LIABILITY FOR INCIDENTAL OR CONSEQUENTIAL DAMAGES – IN THAT SCENARIO, SOME OF THE ABOVE LIMITATIONS MAY NOT BE APPLICABLE IN YOUR CASE.
    Limitation of Liability
    Pandri Market Private Limited will not be responsible or liable for any special, incidental, indirect or consequential damages of any kind in connection with this agreement, even if Pandri Market Private Limited has been informed in advance. This includes
    1) the lack or the inability to use the website content or products; 
    (2) the cost of procuring substitute products or content; 
    (3) any products purchased or obtained or transactions entered into through the website; or 
    (4) any lost profits you claim or allege.
    Furthermore, it needs to be mentioned that in case of certain jurisdictions which does not allow the limitation or exclusion of liability for incidental or consequential damages – in that scenario, some of the above limitations may not be applicable in your case. 
    Indemnification
    You agree to indemnify and hold Pandri Market Private Limited (and its officers, directors, agents, contractors, subsidiaries, affiliates, joint ventures, and employees) harmless from any claim or demand, including but not limited to reasonable attorneys' fees, or arising out of or related to your breach of this T&C, or your violation of any law or the rights of a third party.
    Pandri Market Private Limited will have the right to participate in any defense by you of a third-party claim related to your use of any of the Website content or Products, with counsel of Pandri Market Private Limited choice at its expensePandri Market Private Limited will reasonably cooperate in any defense by you of a third-party claim at your request and expense. You will have sole responsibility to defend Pandri Market Private Limited against any claim, but you must receive Pandri Market Private Limited prior written consent regarding any related settlement. The terms of this provision will survive any termination or cancellation of this Agreement or your use of the Website or Products.
    Proprietary Rights: Intellectual Property, Software, and Content
    The content available on this website is under worldwide copyright protection laws and hence is the sole property of Pandri Market Private Limited. Modification, misuse, translation or creation of derivative work on the basis of website content is highly prohibited.
    Pandri Market Private Limited grants you a limited license to access and make personal use of the Site and the Service. This license does not include any downloading or copying of account information for the benefit of another vendor or any other third party; caching, unauthorized hypertext links to the Site and the framing of any Content available through the Site uploading, posting, or transmitting any content that you do not have a right to make available (such as the intellectual property of another party); uploading, posting, or transmitting any material that contains software viruses or any other computer code, files or programs designed to interrupt, destroy or limit the functionality of any computer software or hardware or telecommunications equipment; any action that imposes or may impose (in Pandri Market Private Limited sole discretion) an unreasonable or disproportionately large load on Pandri Market Private Limited  infrastructure; or any use of data mining, robots, or similar data gathering and extraction tools. You may not bypass any measures used by Pandri Market Private Limited to prevent or restrict access to the Site. Any unauthorized use by you shall terminate the permission or license granted to you by Pandri Market Private Limited. 
    Ix . AGREEMENT TO BE BOUND
    By using this Website or ordering Products, you acknowledge that you have read and agree to be bound by this Agreement and all terms and conditions on this Website. 
    
    x. GENERAL
    Force Majeure
    Pandri Market Private Limited will not be deemed in default hereunder or held responsible for any cessation, interruption or delay in the performance of its obligations hereunder due to earthquake, flood, fire, storm, natural disaster, an act of God, war, terrorism, armed conflict, labor strike, lockout, or boycott.
    Cessation of Operation
     Pandri Market Private Limited may at any time, in its sole discretion and without advance notice to you, cease operation of the Website and distribution of the Products.
    Entire Agreement
     This Agreement comprises the entire agreement between you and Pandri Market Private Limited and supersedes any prior agreements pertaining to the subject matter contained herein.
    Effect of Waiver
    The failure Pandri Market Private Limited to exercise or enforce any right or provision of this Agreement will not constitute a waiver of such right or provision. If any provision of this Agreement is found by a court of competent jurisdiction to be invalid, the parties nevertheless agree that the court should endeavor to give effect to the parties' intentions as reflected in the provision, and the other provisions of this Agreement remain in full force and effect.
    Statute of Limitation
    You agree that regardless of any statute or law to the contrary, any claim or cause of action arising out of or related to use of the Website or Products or this Agreement must be filed within one (1) year after such claim or cause of action arose or be forever barred.
    Waiver of Class Action Rights
     BY ENTERING INTO THIS AGREEMENT, YOU HEREBY IRREVOCABLY WAIVE ANY RIGHT YOU MAY HAVE TO JOIN CLAIMS WITH THOSE OF OTHER IN THE FORM OF A CLASS ACTION OR SIMILAR PROCEDURAL DEVICE. ANY CLAIMS ARISING OUT OF, RELATING TO, OR CONNECTION WITH THIS AGREEMENT MUST BE ASSERTED INDIVIDUALLY.
    Domestic Use
     Pandri Market Private Limited makes no representation that the Website or Products are appropriate or available for use in locations outside India. Users who access the Website from outside India do so at their own risk and initiative and must bear all responsibility for compliance with any applicable local laws.
    Assignment. You may not assign your rights and obligations under this Agreement to anyone. Pandri Market Private Limited may assign its rights and obligations under this Agreement in its sole discretion and without advance notice to you.
    Termination and Survival of Terms After Agreement Ends
    The Company may terminate this Agreement at any time. Without limiting the foregoing, the Company shall have the right to immediately terminate any passwords or accounts of the User in the event of any conduct by the User which the Company, in its sole discretion, considers to be unacceptable, or in the event of any breach by the User of this Agreement. Following termination, you will not be permitted to use the Website and Pandri Market Private Limited may, in its sole discretion and without advance notice to you, cancel any outstanding orders for Products.  Notwithstanding any other provisions of this T&C or any general legal principles to the contrary, any provision of this T&C that imposes or contemplates continuing obligations on a party will survive the expiration or termination of this T&C. 
    
    Miscellaneous
    If any of these conditions are deemed invalid, void, or for any reason unenforceable, the parties agree that the court should endeavor to give effect to the parties' intentions as reflected in the provision, and the unenforceable condition shall be deemed severable and shall not affect the validity and enforceability of any remaining condition. From time to time Pandri Market Private Limited may offer special promotional offers which may or may not apply to your pandrimarket.com account. To avail of such promotional offers, you agree to be bound by any additional terms and conditions for these special offers which are laid down by Pandri Market Private Limited. This T&C and the relationship between you and Pandri Market  Private Limited. will be governed by the laws as applicable in India. Any disputes will be handled in the competent courts of Raipur, India. The failure of Pandri Market Private Limited to act with respect to a breach by you or others does not waive its right to act with respect to subsequent or similar breaches. Pandri Market Private Limited does not guarantee it will take action against all breaches of this T&C. Except as otherwise, expressly provided in this T&C, there shall be no third-party beneficiaries to this T&C. This T&C constitutes the entire agreement between you and Pandri Market Private Limited and governs your use of the Site, superseding any prior agreements between you and Pandri Market Private Limited with respect to the Site.
    Governing Law & Jurisdiction
     This Website originates from Raipur, Chhattisgarh. This Agreement will be governed by the laws of the State of Chhattisgarh without regard to its conflict of law principles to the contrary. Neither you nor Pandri Market Private Limited will commence or prosecute any suit, proceeding or claim to enforce the provisions of this Agreement, to recover damages for breach of or default of this Agreement, or otherwise arising under or by reason of this Agreement, other than in courts located in State Chhattisgarh. By using this Website or ordering Products, you consent to the jurisdiction and venue of such courts in connection with any action, suit, proceeding or claim arising under or by reason of this Agreement. You hereby waive any right to trial by jury arising out of this Agreement and any related documents.
    BY USING THIS WEBSITE OR ORDERING PRODUCTS FROM THIS WEBSITE YOU AGREE 
    TO BE BOUND BY ALL OF THE TERMS AND CONDITIONS OF THIS AGREEMENT.
    
`;
  return (
    <div className={styled.container}>
      <h1>Terms & Conditions</h1>
      <div className="text">{termsAndConditionsText}</div>
    </div>
  );
};

export default TermsAndConditions;
